export const responseBody = {
  results: [
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: null,
      backdrop_path: null,
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: 'ab123',
      backdrop_path: 'ab123',
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
  ],
};

export const actionPayload = [
  {
    id: 475303,
    poster: 'test-file-stub',
    background: 'test-file-stub',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
  {
    id: 475303,
    poster: 'https://image.tmdb.org/t/p/w342ab123',
    background: 'https://image.tmdb.org/t/p/w1280ab123',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
];

export const responseBodyOneMovie = {
  results: [
    {
      id: 475303,
      genre_ids: [0, 1, 2],
      poster_path: null,
      backdrop_path: null,
      title: 'Film',
      vote_average: 5,
      overview: 'film overview',
      viewInfo: false,
    },
  ],
};

export const actionPayloadOneMovie = [
  {
    id: 475303,
    poster: 'test-file-stub',
    background: 'test-file-stub',
    title: 'Film',
    rating: 5,
    overview: 'film overview',
    genres: 'Action, Adventure, Animation',
    viewInfo: false,
  },
];
